<?php

return [
    App\Core\Announcement\Providers\AnnouncementServiceProvider::class,
    App\Core\Assets\Providers\AssetsServiceProvider::class,
    App\Core\Audit\Providers\AuditServiceProvider::class,
    App\Core\Auth\Permission\Providers\PermissionServiceProvider::class,
    App\Core\Auth\Role\Providers\RoleServiceProvider::class,
    App\Core\Auth\User\Providers\AuthUserServiceProvider::class,
    App\Core\Cpanel\Providers\CpanelServiceProvider::class,
    App\Core\Dashboard\Providers\DashboardServiceProvider::class,
    App\Core\Files\Providers\FilesServiceProvider::class,
    App\Core\Identity\Providers\FortifyServiceProvider::class,
    App\Core\Identity\Providers\UserServiceProvider::class,
    App\Core\Notification\Providers\NotificationServiceProvider::class,
    App\Core\Queue\Providers\QueueManagerServiceProvider::class,
    App\Core\Scheduler\Providers\SchedulerServiceProvider::class,
    App\Core\Settings\Providers\SettingServiceProvider::class,
    App\Core\WeatherApi\Providers\WeatherApiServiceProvider::class,
    App\Core\Zoom\Providers\ZoomServiceProvider::class,
    App\Domains\Providers\DomainServiceProvider::class,
    App\Providers\AppServiceProvider::class,
    App\Providers\FilamentNavigationServiceProvider::class,
    App\Providers\Filament\AdminDashboardPanelProvider::class,
    App\Providers\TelescopeServiceProvider::class,
    App\Providers\VoltServiceProvider::class,
];
