<?php

return [
    ['key' => 'plans.enabled', 'value' => 'true', 'display_name' => 'Plans Enabled', 'description' => 'Enable the Plans domain.', 'type' => 'select', 'group' => 'plans', 'options' => ['true' => 'Yes', 'false' => 'No'], 'order' => 1, 'is_visible' => true, 'is_public' => false, 'is_required' => false, 'encrypted' => false],
    ['key' => 'plans.rasterizer_driver', 'value' => 'imagick', 'display_name' => 'Rasterizer Driver', 'description' => 'PDF rasterizer used by the Plans pipeline.', 'type' => 'select', 'group' => 'plans', 'options' => ['poppler' => 'Poppler', 'imagick' => 'Imagick'], 'order' => 2, 'is_visible' => true, 'is_public' => false, 'is_required' => true, 'encrypted' => false],
    ['key' => 'plans.poppler_bin_path', 'value' => '', 'display_name' => 'Poppler Binary Path', 'description' => 'Directory containing pdfinfo and pdftoppm.', 'type' => 'text', 'group' => 'plans', 'order' => 3, 'is_visible' => true, 'is_public' => false, 'is_required' => false, 'encrypted' => false],
    ['key' => 'plans.render_dpi', 'value' => '150', 'display_name' => 'Render DPI', 'description' => 'DPI used when rasterizing pages.', 'type' => 'number', 'group' => 'plans', 'order' => 4, 'is_visible' => true, 'is_public' => false, 'is_required' => true, 'encrypted' => false],
    ['key' => 'plans.thumbnail_width', 'value' => '320', 'display_name' => 'Thumbnail Width', 'description' => 'Thumbnail width in pixels.', 'type' => 'number', 'group' => 'plans', 'order' => 5, 'is_visible' => true, 'is_public' => false, 'is_required' => true, 'encrypted' => false],
    ['key' => 'plans.preview_width', 'value' => '2000', 'display_name' => 'Preview Width', 'description' => 'Preview width in pixels.', 'type' => 'number', 'group' => 'plans', 'order' => 6, 'is_visible' => true, 'is_public' => false, 'is_required' => true, 'encrypted' => false],
    ['key' => 'plans.enable_tiles', 'value' => 'false', 'display_name' => 'Enable Tiles', 'description' => 'Generate tiles for very large sheets.', 'type' => 'select', 'group' => 'plans', 'options' => ['true' => 'Yes', 'false' => 'No'], 'order' => 7, 'is_visible' => true, 'is_public' => false, 'is_required' => false, 'encrypted' => false],
    ['key' => 'plans.derivative_format', 'value' => 'webp', 'display_name' => 'Derivative Format', 'description' => 'Format for generated derivatives.', 'type' => 'select', 'group' => 'plans', 'options' => ['webp' => 'WebP', 'png' => 'PNG'], 'order' => 8, 'is_visible' => true, 'is_public' => false, 'is_required' => true, 'encrypted' => false],
    ['key' => 'plans.storage_disk', 'value' => 'local', 'display_name' => 'Derivative Storage Disk', 'description' => 'Private disk for generated derivatives.', 'type' => 'select', 'group' => 'plans', 'options' => ['local' => 'Local'], 'order' => 9, 'is_visible' => true, 'is_public' => false, 'is_required' => true, 'encrypted' => false],
    ['key' => 'plans.max_pages_per_set', 'value' => '500', 'display_name' => 'Maximum Pages Per Set', 'description' => 'Maximum pages accepted for one plan set.', 'type' => 'number', 'group' => 'plans', 'order' => 10, 'is_visible' => true, 'is_public' => false, 'is_required' => true, 'encrypted' => false],
    ['key' => 'plans.max_upload_kilobytes', 'value' => '512000', 'display_name' => 'Maximum Upload Size', 'description' => 'Maximum plan set upload size in kilobytes.', 'type' => 'number', 'group' => 'plans', 'order' => 11, 'is_visible' => true, 'is_public' => false, 'is_required' => true, 'encrypted' => false],
    ['key' => 'plans.title_block_region', 'value' => 'bottom-right', 'display_name' => 'Title Block Region', 'description' => 'Region used for sheet number detection.', 'type' => 'text', 'group' => 'plans', 'order' => 12, 'is_visible' => true, 'is_public' => false, 'is_required' => true, 'encrypted' => false],
    ['key' => 'plans.sheet_number_pattern', 'value' => '(?<![A-Z0-9])[A-Z]{1,3}[\\s.-]?\\d{1,3}(?:\\.\\d+)?(?![A-Z0-9])', 'display_name' => 'Sheet Number Format', 'description' => 'Choose the sheet number style to detect. Use Common construction sheets for values like A 0.05, H 0.01, E1, FA 0.01, and A-101.', 'type' => 'select', 'group' => 'plans', 'options' => ['(?<![A-Z0-9])[A-Z]{1,3}[\\s.-]?\\d{1,3}(?:\\.\\d+)?(?![A-Z0-9])' => 'Common construction sheets - A 0.05, H 0.01, E1, FA 0.01, A-101', '(?<![A-Z0-9])[A-Z]{1,3}[\\s.-]\\d{1,3}\\.\\d+(?![A-Z0-9])' => 'Decimal sheets only - A 0.05, H 0.01, E 2.03', '(?<![A-Z0-9])[A-Z]{1,3}[-.]?\\d{1,3}(?:\\.\\d+)?(?![A-Z0-9])' => 'Compact or hyphenated sheets - A101, A-101, FA001'], 'order' => 13, 'is_visible' => true, 'is_public' => false, 'is_required' => true, 'encrypted' => false],
    ['key' => 'plans.ocr_driver', 'value' => 'google-vision', 'display_name' => 'OCR Driver', 'description' => 'OCR provider used when a sheet has no PDF text layer.', 'type' => 'select', 'group' => 'plans', 'options' => ['google-vision' => 'Google Vision', 'tesseract' => 'Tesseract'], 'order' => 14, 'is_visible' => true, 'is_public' => false, 'is_required' => true, 'encrypted' => false],
    ['key' => 'plans.ocr_fallback_enabled', 'value' => 'false', 'display_name' => 'OCR Fallback Enabled', 'description' => 'Run OCR when the PDF text layer is empty or too short. Incurs per-page provider cost.', 'type' => 'select', 'group' => 'plans', 'options' => ['true' => 'Yes', 'false' => 'No'], 'order' => 15, 'is_visible' => true, 'is_public' => false, 'is_required' => false, 'encrypted' => false],
    ['key' => 'plans.ocr_min_text_length', 'value' => '12', 'display_name' => 'OCR Fallback Minimum Text Length', 'description' => 'Text-layer character count below which OCR fallback triggers.', 'type' => 'number', 'group' => 'plans', 'order' => 16, 'is_visible' => true, 'is_public' => false, 'is_required' => true, 'encrypted' => false],
];
