<?php

namespace App\PlugIns\Cpanel\Settings;

use App\Core\Settings\Contracts\SettingsRegistryContract;
use App\Core\Settings\DTO\Setting;
use App\Core\Settings\DTO\SettingFormFieldType;
use App\Core\Settings\DTO\SettingType;

class CPanelSettings implements SettingsRegistryContract
{

    public const GROUP = 'cpanel';
    public static function definitions(): array
    {
        return [
            new Setting(
                key: 'cpanel.enabled',
                type: SettingType::BOOLEAN,
                formFieldType: SettingFormFieldType::TOGGLE,
                value: env('CPANEL_ENABLED', false),
                display_name: 'CPanel Enabled',
                description: 'Enable or disable CPanel integration.',
                group: self::GROUP,
                options: null,
                order: 1,
                is_visible: true,
                is_public: false,
                is_required: false,
                encrypted: false,
            ),
            new Setting(
                key: 'cpanel.url',
                type: SettingType::STRING,
                formFieldType: SettingFormFieldType::TEXT,
                value: env('CPANEL_URL', ''),
                display_name: 'cPanel URL',
                description: 'cPanel server URL (including protocol).',
                group: self::GROUP,
                options: null,
                order: 2,
                is_visible: true,
                is_public: false,
                is_required: false,
                encrypted: false,
            ),
            new Setting(
                key: 'cpanel.username',
                type: SettingType::STRING,
                formFieldType: SettingFormFieldType::TEXT,
                value: env('CPANEL_USERNAME', ''),
                display_name: 'cPanel Username',
                description: 'cPanel username used for API auth.',
                group: self::GROUP,
                options: null,
                order: 3,
                is_visible: true,
                is_public: false,
                is_required: false,
                encrypted: false,
            ),
            new Setting(
                key: 'cpanel.api_token',
                type: SettingType::STRING,
                formFieldType: SettingFormFieldType::PASSWORD,
                value: env('CPANEL_API_TOKEN', ''),
                display_name: 'cPanel API Token',
                description: 'API token used for cPanel requests.',
                group: self::GROUP,
                options: null,
                order: 4,
                is_visible: true,
                is_public: false,
                is_required: false,
                encrypted: true,
            ),
            new Setting(
                key: 'cpanel.domain',
                type: SettingType::STRING,
                formFieldType: SettingFormFieldType::TEXT,
                value: env('CPANEL_DOMAIN', ''),
                display_name: 'cPanel Domain',
                description: 'Default domain used for mailbox operations.',
                group: self::GROUP,
                options: null,
                order: 5,
                is_visible: true,
                is_public: false,
                is_required: false,
                encrypted: false,
            ),
            new Setting(
                key: 'cpanel.port',
                type: SettingType::INTEGER,
                formFieldType: SettingFormFieldType::NUMBER,
                value: env('CPANEL_PORT', 2083),
                display_name: 'cPanel Port',
                description: 'cPanel API port.',
                group: self::GROUP,
                options: null,
                order: 6,
                is_visible: true,
                is_public: false,
                is_required: false,
                encrypted: false,
            ),
            new Setting(
                key: 'cpanel.webmail_port',
                type: SettingType::INTEGER,
                formFieldType: SettingFormFieldType::NUMBER,
                value: env('CPANEL_WEBMAIL_PORT', 2096),
                display_name: 'cPanel Webmail Port',
                description: 'Webmail port for redirect fallback.',
                group: self::GROUP,
                options: null,
                order: 7,
                is_visible: true,
                is_public: false,
                is_required: false,
                encrypted: false,
            ),
            new Setting(
                key: 'cpanel.webmail_url',
                type: SettingType::STRING,
                formFieldType: SettingFormFieldType::TEXT,
                value: env('CPANEL_WEBMAIL_URL', ''),
                display_name: 'cPanel Webmail URL',
                description: 'Optional explicit webmail URL.',
                group: self::GROUP,
                options: null,
                order: 8,
                is_visible: true,
                is_public: false,
                is_required: false,
                encrypted: false,
            ),
            new Setting(
                key: 'cpanel.default_email_quota',
                type: SettingType::INTEGER,
                formFieldType: SettingFormFieldType::NUMBER,
                value: env('CPANEL_DEFAULT_EMAIL_QUOTA', 250),
                display_name: 'cPanel Default Email Quota (MB)',
                description: 'Default mailbox quota in MB.',
                group: self::GROUP,
                options: null,
                order: 9,
                is_visible: true,
                is_public: false,
                is_required: false,
                encrypted: false,
            ),
            new Setting(
                key: 'cpanel.auto_create_emails',
                type: SettingType::STRING,
                formFieldType: SettingFormFieldType::SELECT,
                value: env('CPANEL_AUTO_CREATE_EMAILS', false) ? 'true' : 'false',
                display_name: 'cPanel Auto Create Emails',
                description: 'Automatically create mailbox accounts for eligible users.',
                group: self::GROUP,
                options: ['true' => 'Yes', 'false' => 'No'],
                order: 10,
                is_visible: true,
                is_public: false,
                is_required: false,
                encrypted: false,
            ),
            new Setting(
                key: 'cpanel.auto_delete_emails',
                type: SettingType::STRING,
                formFieldType: SettingFormFieldType::SELECT,
                value: env('CPANEL_AUTO_DELETE_EMAILS', true) ? 'true' : 'false',
                display_name: 'cPanel Auto Delete Emails',
                description: 'Delete mailbox accounts when users are deleted.',
                group: self::GROUP,
                options: ['true' => 'Yes', 'false' => 'No'],
                order: 11,
                is_visible: true,
                is_public: false,
                is_required: false,
                encrypted: false,
            ),
            new Setting(
                key: 'cpanel.sync_user_passwords',
                type: SettingType::STRING,
                formFieldType: SettingFormFieldType::SELECT,
                value: env('CPANEL_SYNC_USER_PASSWORDS', false) ? 'true' : 'false',
                display_name: 'cPanel Sync User Passwords',
                description: 'Sync application password changes to mailbox accounts.',
                group: self::GROUP,
                options: ['true' => 'Yes', 'false' => 'No'],
                order: 12,
                is_visible: true,
                is_public: false,
                is_required: false,
                encrypted: false,
            ),
            new Setting(
                key: 'cpanel.queue_write_operations',
                type: SettingType::STRING,
                formFieldType: SettingFormFieldType::SELECT,
                value: env('CPANEL_QUEUE_WRITE_OPERATIONS', false) ? 'true' : 'false',
                display_name: 'cPanel Queue Write Operations',
                description: 'Queue write-side cPanel operations for resilience.',
                group: self::GROUP,
                options: ['true' => 'Yes', 'false' => 'No'],
                order: 13,
                is_visible: true,
                is_public: false,
                is_required: false,
                encrypted: false,
            ),
            new Setting(
                key: 'cpanel.idempotency_ttl_seconds',
                type: SettingType::INTEGER,
                formFieldType: SettingFormFieldType::NUMBER,
                value: env('CPANEL_IDEMPOTENCY_TTL_SECONDS', 120),
                display_name: 'cPanel Idempotency TTL (Seconds)',
                description: 'Deduplicate repeated write operations within this window.',
                group: self::GROUP,
                options: null,
                order: 14,
                is_visible: true,
                is_public: false,
                is_required: false,
                encrypted: false,
            ),
            new Setting(
                key: 'cpanel.queue_tries',
                type: SettingType::INTEGER,
                formFieldType: SettingFormFieldType::NUMBER,
                value: env('CPANEL_QUEUE_TRIES', 3),
                display_name: 'cPanel Queue Retries',
                description: 'Maximum number of attempts for queued write operations.',
                group: self::GROUP,
                options: null,
                order: 15,
                is_visible: true,
                is_public: false,
                is_required: false,
                encrypted: false,
            ),
            new Setting(
                key: 'cpanel.queue_backoff',
                type: SettingType::STRING,
                formFieldType: SettingFormFieldType::TEXT,
                value: env('CPANEL_QUEUE_BACKOFF', ''),
                display_name: 'cPanel Queue Backoff',
                description: 'Comma-separated backoff seconds for queued retries.',
                group: self::GROUP,
                options: null,
                order: 16,
                is_visible: true,
                is_public: false,
                is_required: false,
                encrypted: false,
            ),
            new Setting(
                key: 'cpanel.failure_threshold',
                type: SettingType::INTEGER,
                formFieldType: SettingFormFieldType::NUMBER,
                value: env('CPANEL_FAILURE_THRESHOLD', 5),
                display_name: 'cPanel Failure Threshold',
                description: 'Consecutive failures before cPanel cooldown activates.',
                group: self::GROUP,
                options: null,
                order: 17,
                is_visible: true,
                is_public: false,
                is_required: false,
                encrypted: false,
            ),
            new Setting(
                key: 'cpanel.cooldown_seconds',
                type: SettingType::INTEGER,
                formFieldType: SettingFormFieldType::NUMBER,
                value: env('CPANEL_COOLDOWN_SECONDS', 300),
                display_name: 'cPanel Cooldown Seconds',
                description: 'Skip write operations while cooldown is active.',
                group: self::GROUP,
                options: null,
                order: 18,
                is_visible: true,
                is_public: false,
                is_required: false,
                encrypted: false,
            ),
            new Setting(
                key: 'cpanel.telemetry_key_prefix',
                type: SettingType::STRING,
                formFieldType: SettingFormFieldType::TEXT,
                value: env('CPANEL_TELEMETRY_KEY_PREFIX', ''),
                display_name: 'cPanel Telemetry Key Prefix',
                description: 'Cache key prefix for cPanel success/failure counters.',
                group: self::GROUP,
                options: null,
                order: 19,
                is_visible: true,
                is_public: false,
                is_required: false,
                encrypted: false,
            ),
            new Setting(
                key: 'cpanel.verify_ssl',
                type: SettingType::STRING,
                formFieldType: SettingFormFieldType::SELECT,
                value: env('CPANEL_VERIFY_SSL', true) ? 'true' : 'false',
                display_name: 'cPanel Verify SSL',
                description: 'Require SSL certificate verification for cPanel API requests.',
                group: self::GROUP,
                options: ['true' => 'Yes', 'false' => 'No'],
                order: 20,
                is_visible: true,
                is_public: false,
                is_required: false,
                encrypted: false,
            ),
        ];
    }
}   