<?php

return [
    [
        'key' => 'app.name',
        'value' => env('APP_NAME', 'Project Manager'),
        'display_name' => 'Application Name',
        'description' => 'The name of your application',
        'type' => 'text',
        'group' => 'app',
        'order' => 1,
        'is_visible' => true,
        'is_public' => true,
        'is_required' => true,
        'encrypted' => false,
    ],
    [
        'key' => 'app.url',
        'value' => env('APP_URL', 'http://localhost'),
        'display_name' => 'Application URL',
        'description' => 'The URL of your application',
        'type' => 'url',
        'group' => 'app',
        'order' => 2,
        'is_visible' => true,
        'is_public' => false,
        'is_required' => true,
        'encrypted' => false,
    ],
    [
        'key' => 'app.timezone',
        'value' => env('APP_TIMEZONE', 'UTC'),
        'display_name' => 'Timezone',
        'description' => 'Application timezone for date/time operations',
        'type' => 'select',
        'group' => 'app',
        'options' => [
            'UTC' => 'UTC (Coordinated Universal Time)',
            'America/New_York' => 'Eastern Time (US & Canada)',
            'America/Chicago' => 'Central Time (US & Canada)',
            'America/Denver' => 'Mountain Time (US & Canada)',
            'America/Los_Angeles' => 'Pacific Time (US & Canada)',
            'America/Anchorage' => 'Alaska Time',
            'America/Adak' => 'Hawaii-Aleutian Time',
            'Europe/London' => 'Greenwich Mean Time',
            'Europe/Paris' => 'Central European Time',
            'Europe/Moscow' => 'Moscow Standard Time',
            'Asia/Dubai' => 'Gulf Standard Time',
            'Asia/Kolkata' => 'Indian Standard Time',
            'Asia/Bangkok' => 'Indochina Time',
            'Asia/Shanghai' => 'China Standard Time',
            'Asia/Seoul' => 'Korea Standard Time',
            'Asia/Tokyo' => 'Japan Standard Time',
            'Australia/Sydney' => 'Australian Eastern Time',
            'Pacific/Auckland' => 'New Zealand Standard Time',
        ],
        'order' => 3,
        'is_visible' => true,
        'is_public' => false,
        'is_required' => true,
        'encrypted' => false,
    ],
    [
        'key' => 'app.debug',
        'value' => env('APP_DEBUG', false) ? 'true' : 'false',
        'display_name' => 'Debug Mode',
        'description' => 'Enable debug mode for development',
        'type' => 'select',
        'group' => 'app',
        'options' => ['true' => 'Enabled', 'false' => 'Disabled'],
        'order' => 4,
        'is_visible' => true,
        'is_public' => false,
        'is_required' => true,
        'encrypted' => false,
    ],
    [
        'key' => 'session.driver',
        'value' => env('SESSION_DRIVER', 'file'),
        'display_name' => 'Session Driver',
        'description' => 'Session storage driver (file, database, redis, etc.)',
        'type' => 'select',
        'group' => 'session',
        'options' => ['file' => 'File', 'database' => 'Database', 'redis' => 'Redis', 'memcached' => 'Memcached', 'array' => 'Array (Testing)'],
        'order' => 1,
        'is_visible' => true,
        'is_public' => false,
        'is_required' => false,
        'encrypted' => false,
    ],
    [
        'key' => 'session.lifetime',
        'value' => (string) env('SESSION_LIFETIME', '120'),
        'display_name' => 'Session Lifetime (minutes)',
        'description' => 'Minutes before session expires',
        'type' => 'number',
        'group' => 'session',
        'order' => 2,
        'is_visible' => true,
        'is_public' => false,
        'is_required' => false,
        'encrypted' => false,
    ],
    [
        'key' => 'session.expire_on_close',
        'value' => env('SESSION_EXPIRE_ON_CLOSE', false) ? 'true' : 'false',
        'display_name' => 'Expire On Browser Close',
        'description' => 'Expire session when browser closes',
        'type' => 'select',
        'group' => 'session',
        'options' => ['true' => 'Yes', 'false' => 'No'],
        'order' => 3,
        'is_visible' => true,
        'is_public' => false,
        'is_required' => false,
        'encrypted' => false,
    ],
    [
        'key' => 'session.encrypt',
        'value' => env('SESSION_ENCRYPT', false) ? 'true' : 'false',
        'display_name' => 'Encrypt Session Data',
        'description' => 'Encrypt all session data',
        'type' => 'select',
        'group' => 'session',
        'options' => ['true' => 'Yes', 'false' => 'No'],
        'order' => 4,
        'is_visible' => true,
        'is_public' => false,
        'is_required' => false,
        'encrypted' => false,
    ],
    [
        'key' => 'system.date_format',
        'value' => env('SYSTEM_DATE_FORMAT', 'Y-m-d'),
        'display_name' => 'Date Format',
        'description' => 'Date format used throughout the system',
        'type' => 'select',
        'group' => 'system',
        'options' => ['Y-m-d' => '2024-01-15', 'm/d/Y' => '01/15/2024', 'd/m/Y' => '15/01/2024', 'M j, Y' => 'Jan 15, 2024'],
        'order' => 1,
        'is_visible' => true,
        'is_public' => true,
        'is_required' => true,
        'encrypted' => false,
    ],
    [
        'key' => 'system.time_format',
        'value' => env('SYSTEM_TIME_FORMAT', 'H:i'),
        'display_name' => 'Time Format',
        'description' => 'Time format used throughout the system',
        'type' => 'select',
        'group' => 'system',
        'options' => ['H:i' => '14:30 (24-hour)', 'g:i A' => '2:30 PM (12-hour)'],
        'order' => 2,
        'is_visible' => true,
        'is_public' => true,
        'is_required' => true,
        'encrypted' => false,
    ],
    [
        'key' => 'system.locale',
        'value' => env('SYSTEM_LOCALE', 'en'),
        'display_name' => 'Default Language',
        'description' => 'Default language for the application',
        'type' => 'select',
        'group' => 'system',
        'options' => ['en' => 'English', 'es' => 'Spanish', 'fr' => 'French'],
        'order' => 3,
        'is_visible' => true,
        'is_public' => true,
        'is_required' => true,
        'encrypted' => false,
    ],
    [
        'key' => 'system.work_hours_per_day',
        'value' => (string) env('SYSTEM_WORK_HOURS_PER_DAY', '8'),
        'display_name' => 'Default Work Hours Per Day',
        'description' => 'Standard number of work hours per day',
        'type' => 'number',
        'group' => 'system',
        'order' => 4,
        'is_visible' => true,
        'is_public' => true,
        'is_required' => false,
        'encrypted' => false,
    ],
    [
        'key' => 'system.log_level',
        'value' => env('LOG_LEVEL', 'error'),
        'display_name' => 'Log Level',
        'description' => 'Logging level for application logs',
        'type' => 'select',
        'group' => 'system',
        'options' => [
            'debug' => 'Debug (Development only - very verbose)',
            'info' => 'Info (Log general information)',
            'notice' => 'Notice (Normal but significant events)',
            'warning' => 'Warning (Recommended for production)',
            'error' => 'Error (Production - only errors and above)',
            'critical' => 'Critical (Only critical issues)',
        ],
        'order' => 5,
        'is_visible' => true,
        'is_public' => false,
        'is_required' => true,
        'encrypted' => false,
    ],
    [
        'key' => 'system.cache_enabled',
        'value' => env('SETTINGS_CACHE_ENABLED', true) ? 'true' : 'false',
        'display_name' => 'Enable Settings Cache',
        'description' => 'Cache settings for improved performance',
        'type' => 'select',
        'group' => 'system',
        'options' => ['true' => 'Enabled', 'false' => 'Disabled'],
        'order' => 6,
        'is_visible' => true,
        'is_public' => false,
        'is_required' => false,
        'encrypted' => false,
    ],
    [
        'key' => 'system.cache_ttl',
        'value' => (string) env('SETTINGS_CACHE_TTL', 3600),
        'display_name' => 'Cache TTL (seconds)',
        'description' => 'How long to cache settings (in seconds)',
        'type' => 'number',
        'group' => 'system',
        'order' => 7,
        'is_visible' => true,
        'is_public' => false,
        'is_required' => false,
        'encrypted' => false,
    ],
    [
        'key' => 'system.log_changes',
        'value' => env('SETTINGS_LOG_CHANGES', false) ? 'true' : 'false',
        'display_name' => 'Log Settings Changes',
        'description' => 'Log all settings changes for audit trail',
        'type' => 'select',
        'group' => 'system',
        'options' => ['true' => 'Enabled', 'false' => 'Disabled'],
        'order' => 8,
        'is_visible' => true,
        'is_public' => false,
        'is_required' => false,
        'encrypted' => false,
    ],
    [
        'key' => 'mail.mailer',
        'value' => env('MAIL_MAILER', 'log'),
        'display_name' => 'Mail Driver',
        'description' => 'Default mailer used for outgoing emails.',
        'type' => 'select',
        'group' => 'mail',
        'options' => [
            'smtp' => 'SMTP',
            'sendmail' => 'Sendmail',
            'log' => 'Log',
            'array' => 'Array (Testing)',
            'ses' => 'Amazon SES',
            'postmark' => 'Postmark',
            'resend' => 'Resend',
        ],
        'order' => 1,
        'is_visible' => true,
        'is_public' => false,
        'is_required' => true,
        'encrypted' => false,
    ],
    [
        'key' => 'mail.host',
        'value' => env('MAIL_HOST', '127.0.0.1'),
        'display_name' => 'SMTP Host',
        'description' => 'SMTP server hostname.',
        'type' => 'text',
        'group' => 'mail',
        'order' => 2,
        'is_visible' => true,
        'is_public' => false,
        'is_required' => false,
        'encrypted' => false,
    ],
    [
        'key' => 'mail.port',
        'value' => (string) env('MAIL_PORT', 2525),
        'display_name' => 'SMTP Port',
        'description' => 'SMTP server port.',
        'type' => 'number',
        'group' => 'mail',
        'order' => 3,
        'is_visible' => true,
        'is_public' => false,
        'is_required' => false,
        'encrypted' => false,
    ],
    [
        'key' => 'mail.encryption',
        'value' => env('MAIL_ENCRYPTION', ''),
        'display_name' => 'Encryption',
        'description' => 'Transport encryption (tls, ssl, or empty).',
        'type' => 'select',
        'group' => 'mail',
        'options' => [
            '' => 'None',
            'tls' => 'TLS',
            'ssl' => 'SSL',
        ],
        'order' => 4,
        'is_visible' => true,
        'is_public' => false,
        'is_required' => false,
        'encrypted' => false,
    ],
    [
        'key' => 'mail.username',
        'value' => env('MAIL_USERNAME', ''),
        'display_name' => 'SMTP Username',
        'description' => 'Username for SMTP authentication.',
        'type' => 'text',
        'group' => 'mail',
        'order' => 5,
        'is_visible' => true,
        'is_public' => false,
        'is_required' => false,
        'encrypted' => false,
    ],
    [
        'key' => 'mail.password',
        'value' => env('MAIL_PASSWORD', ''),
        'display_name' => 'SMTP Password',
        'description' => 'Password for SMTP authentication.',
        'type' => 'password',
        'group' => 'mail',
        'order' => 6,
        'is_visible' => true,
        'is_public' => false,
        'is_required' => false,
        'encrypted' => true,
    ],
    [
        'key' => 'mail.from_address',
        'value' => env('MAIL_FROM_ADDRESS', 'hello@example.com'),
        'display_name' => 'From Address',
        'description' => 'Default sender email address.',
        'type' => 'email',
        'group' => 'mail',
        'order' => 7,
        'is_visible' => true,
        'is_public' => false,
        'is_required' => true,
        'encrypted' => false,
    ],
    [
        'key' => 'mail.from_name',
        'value' => env('MAIL_FROM_NAME', 'Example'),
        'display_name' => 'From Name',
        'description' => 'Default sender display name.',
        'type' => 'text',
        'group' => 'mail',
        'order' => 8,
        'is_visible' => true,
        'is_public' => false,
        'is_required' => true,
        'encrypted' => false,
    ],
    [
        'key' => 'security.session_timeout',
        'value' => (string) env('SECURITY_SESSION_TIMEOUT', '120'),
        'display_name' => 'Session Timeout (minutes)',
        'description' => 'Maximum idle session duration before logout.',
        'type' => 'number',
        'group' => 'security',
        'order' => 1,
        'is_visible' => true,
        'is_public' => false,
        'is_required' => false,
        'encrypted' => false,
    ],
    [
        'key' => 'features.maintenance_mode',
        'value' => env('FEATURES_MAINTENANCE_MODE', false) ? 'true' : 'false',
        'display_name' => 'Maintenance Mode',
        'description' => 'Enable maintenance mode banner/behavior for the application.',
        'type' => 'select',
        'group' => 'features',
        'options' => ['true' => 'Enabled', 'false' => 'Disabled'],
        'order' => 1,
        'is_visible' => true,
        'is_public' => false,
        'is_required' => false,
        'encrypted' => false,
    ],
];
