<?php

return [
    [
        'key' => 'storage.default_disk',
        'value' => env('FILESYSTEM_DISK', 'local'),
        'display_name' => 'Default Storage Disk',
        'description' => 'Default filesystem disk used across the application when a domain does not choose its own.',
        'type' => 'select',
        'group' => 'storage',
        'options' => \App\Core\Assets\Support\StorageDiskOptions::all(),
        'order' => 1,
        'is_visible' => true,
        'is_public' => false,
        'is_required' => false,
        'encrypted' => false,
    ],

    // Amazon S3
    [
        'key' => 'storage.s3.access_key_id',
        'value' => env('AWS_ACCESS_KEY_ID', ''),
        'display_name' => 'AWS Access Key ID',
        'description' => 'IAM access key ID used to authenticate with the S3 bucket.',
        'type' => 'password',
        'group' => 'storage',
        'order' => 10,
        'is_visible' => true,
        'is_public' => false,
        'is_required' => false,
        'encrypted' => true,
    ],
    [
        'key' => 'storage.s3.secret_access_key',
        'value' => env('AWS_SECRET_ACCESS_KEY', ''),
        'display_name' => 'AWS Secret Access Key',
        'description' => 'IAM secret access key used to authenticate with the S3 bucket.',
        'type' => 'password',
        'group' => 'storage',
        'order' => 11,
        'is_visible' => true,
        'is_public' => false,
        'is_required' => false,
        'encrypted' => true,
    ],
    [
        'key' => 'storage.s3.region',
        'value' => env('AWS_DEFAULT_REGION', ''),
        'display_name' => 'AWS Region',
        'description' => 'AWS region the S3 bucket lives in, e.g. us-east-1.',
        'type' => 'text',
        'group' => 'storage',
        'order' => 12,
        'is_visible' => true,
        'is_public' => false,
        'is_required' => false,
        'encrypted' => false,
    ],
    [
        'key' => 'storage.s3.bucket',
        'value' => env('AWS_BUCKET', ''),
        'display_name' => 'AWS Bucket',
        'description' => 'S3 bucket name used for file storage.',
        'type' => 'text',
        'group' => 'storage',
        'order' => 13,
        'is_visible' => true,
        'is_public' => false,
        'is_required' => false,
        'encrypted' => false,
    ],
    [
        'key' => 'storage.s3.url',
        'value' => env('AWS_URL', ''),
        'display_name' => 'AWS URL',
        'description' => 'Optional public base URL (e.g. CDN domain) used when generating S3 file URLs.',
        'type' => 'text',
        'group' => 'storage',
        'order' => 14,
        'is_visible' => true,
        'is_public' => false,
        'is_required' => false,
        'encrypted' => false,
    ],
    [
        'key' => 'storage.s3.endpoint',
        'value' => env('AWS_ENDPOINT', ''),
        'display_name' => 'AWS Endpoint',
        'description' => 'Optional custom endpoint for S3-compatible services (e.g. DigitalOcean Spaces, MinIO, Cloudflare R2).',
        'type' => 'text',
        'group' => 'storage',
        'order' => 15,
        'is_visible' => true,
        'is_public' => false,
        'is_required' => false,
        'encrypted' => false,
    ],
    [
        'key' => 'storage.s3.use_path_style_endpoint',
        'value' => env('AWS_USE_PATH_STYLE_ENDPOINT', false) ? 'true' : 'false',
        'display_name' => 'Use Path-Style Endpoint',
        'description' => 'Enable for S3-compatible services that require path-style URLs instead of virtual-hosted-style.',
        'type' => 'select',
        'group' => 'storage',
        'options' => ['true' => 'Yes', 'false' => 'No'],
        'order' => 16,
        'is_visible' => true,
        'is_public' => false,
        'is_required' => false,
        'encrypted' => false,
    ],

    // SFTP
    [
        'key' => 'storage.sftp.host',
        'value' => env('SFTP_HOST', ''),
        'display_name' => 'SFTP Host',
        'description' => 'Hostname or IP address of the SFTP server.',
        'type' => 'text',
        'group' => 'storage',
        'order' => 20,
        'is_visible' => true,
        'is_public' => false,
        'is_required' => false,
        'encrypted' => false,
    ],
    [
        'key' => 'storage.sftp.username',
        'value' => env('SFTP_USERNAME', ''),
        'display_name' => 'SFTP Username',
        'description' => 'Username used to authenticate with the SFTP server.',
        'type' => 'text',
        'group' => 'storage',
        'order' => 21,
        'is_visible' => true,
        'is_public' => false,
        'is_required' => false,
        'encrypted' => false,
    ],
    [
        'key' => 'storage.sftp.password',
        'value' => env('SFTP_PASSWORD', ''),
        'display_name' => 'SFTP Password',
        'description' => 'Password used to authenticate with the SFTP server (leave blank when using a private key).',
        'type' => 'password',
        'group' => 'storage',
        'order' => 22,
        'is_visible' => true,
        'is_public' => false,
        'is_required' => false,
        'encrypted' => true,
    ],
    [
        'key' => 'storage.sftp.private_key',
        'value' => env('SFTP_PRIVATE_KEY', ''),
        'display_name' => 'SFTP Private Key Path',
        'description' => 'Absolute path to a private key file used to authenticate with the SFTP server (leave blank when using a password).',
        'type' => 'password',
        'group' => 'storage',
        'order' => 23,
        'is_visible' => true,
        'is_public' => false,
        'is_required' => false,
        'encrypted' => true,
    ],
    [
        'key' => 'storage.sftp.port',
        'value' => (string) env('SFTP_PORT', '22'),
        'display_name' => 'SFTP Port',
        'description' => 'Port number the SFTP server listens on.',
        'type' => 'number',
        'group' => 'storage',
        'order' => 24,
        'is_visible' => true,
        'is_public' => false,
        'is_required' => false,
        'encrypted' => false,
    ],
    [
        'key' => 'storage.sftp.root',
        'value' => env('SFTP_ROOT', ''),
        'display_name' => 'SFTP Root Path',
        'description' => 'Root directory on the SFTP server files are stored under.',
        'type' => 'text',
        'group' => 'storage',
        'order' => 25,
        'is_visible' => true,
        'is_public' => false,
        'is_required' => false,
        'encrypted' => false,
    ],
];
