<?php

return [
    [
        'key' => 'zoom.account_id',
        'value' => env('ZOOM_ACCOUNT_ID', ''),
        'display_name' => 'Zoom Account ID',
        'description' => 'Zoom Server-to-Server OAuth account identifier.',
        'type' => 'text',
        'group' => 'services',
        'order' => 1,
        'is_visible' => true,
        'is_public' => false,
        'is_required' => false,
        'encrypted' => false,
    ],
    [
        'key' => 'zoom.client_id',
        'value' => env('ZOOM_CLIENT_ID', ''),
        'display_name' => 'Zoom Client ID',
        'description' => 'Zoom OAuth client ID used for SMS API authentication.',
        'type' => 'text',
        'group' => 'services',
        'order' => 2,
        'is_visible' => true,
        'is_public' => false,
        'is_required' => false,
        'encrypted' => false,
    ],
    [
        'key' => 'zoom.client_secret',
        'value' => env('ZOOM_CLIENT_SECRET', ''),
        'display_name' => 'Zoom Client Secret',
        'description' => 'Zoom OAuth client secret used for token acquisition.',
        'type' => 'password',
        'group' => 'services',
        'order' => 3,
        'is_visible' => true,
        'is_public' => false,
        'is_required' => false,
        'encrypted' => true,
    ],
    [
        'key' => 'zoom.token_url',
        'value' => env('ZOOM_TOKEN_URL', 'https://zoom.us/oauth/token'),
        'display_name' => 'Zoom Token URL',
        'description' => 'OAuth token endpoint for Zoom Server-to-Server credentials.',
        'type' => 'url',
        'group' => 'services',
        'order' => 4,
        'is_visible' => true,
        'is_public' => false,
        'is_required' => false,
        'encrypted' => false,
    ],
    [
        'key' => 'zoom.from_number',
        'value' => env('ZOOM_SMS_FROM_NUMBER', ''),
        'display_name' => 'Zoom SMS From Number',
        'description' => 'E.164 sender phone number used for outbound SMS.',
        'type' => 'text',
        'group' => 'services',
        'order' => 5,
        'is_visible' => true,
        'is_public' => false,
        'is_required' => false,
        'encrypted' => false,
    ],
    [
        'key' => 'zoom.zoom_user_id',
        'value' => env('ZOOM_USER_ID', ''),
        'display_name' => 'Zoom User ID',
        'description' => 'Zoom user ID owning the sender number for consent lookups.',
        'type' => 'text',
        'group' => 'services',
        'order' => 6,
        'is_visible' => true,
        'is_public' => false,
        'is_required' => false,
        'encrypted' => false,
    ],
    [
        'key' => 'zoom.sms_campaign_id',
        'value' => env('ZOOM_SMS_CAMPAIGN_ID', ''),
        'display_name' => 'Zoom SMS Campaign ID',
        'description' => 'Campaign identifier used for consent status synchronization.',
        'type' => 'text',
        'group' => 'services',
        'order' => 7,
        'is_visible' => true,
        'is_public' => false,
        'is_required' => false,
        'encrypted' => false,
    ],
    [
        'key' => 'zoom.api_base_url',
        'value' => env('ZOOM_API_BASE_URL', 'https://api.zoom.us/v2'),
        'display_name' => 'Zoom API Base URL',
        'description' => 'Base API URL used for Zoom SMS and consent endpoints.',
        'type' => 'url',
        'group' => 'services',
        'order' => 8,
        'is_visible' => true,
        'is_public' => false,
        'is_required' => false,
        'encrypted' => false,
    ],
    [
        'key' => 'zoom.token_cache_ttl',
        'value' => (string) env('ZOOM_TOKEN_CACHE_TTL', 3590),
        'display_name' => 'Zoom Token Cache TTL (Seconds)',
        'description' => 'Token cache duration in seconds before requesting a new token.',
        'type' => 'number',
        'group' => 'services',
        'order' => 9,
        'is_visible' => true,
        'is_public' => false,
        'is_required' => false,
        'encrypted' => false,
    ],
    [
        'key' => 'zoom.timeout',
        'value' => (string) env('ZOOM_TIMEOUT', 15),
        'display_name' => 'Zoom Request Timeout (Seconds)',
        'description' => 'HTTP request timeout for Zoom API calls.',
        'type' => 'number',
        'group' => 'services',
        'order' => 10,
        'is_visible' => true,
        'is_public' => false,
        'is_required' => false,
        'encrypted' => false,
    ],
    [
        'key' => 'zoom.retry_times',
        'value' => (string) env('ZOOM_RETRY_TIMES', 3),
        'display_name' => 'Zoom Retry Attempts',
        'description' => 'Number of retry attempts for transient Zoom API failures.',
        'type' => 'number',
        'group' => 'services',
        'order' => 11,
        'is_visible' => true,
        'is_public' => false,
        'is_required' => false,
        'encrypted' => false,
    ],
    [
        'key' => 'zoom.retry_sleep_ms',
        'value' => (string) env('ZOOM_RETRY_SLEEP_MS', 1000),
        'display_name' => 'Zoom Retry Sleep (Milliseconds)',
        'description' => 'Delay between retry attempts in milliseconds.',
        'type' => 'number',
        'group' => 'services',
        'order' => 12,
        'is_visible' => true,
        'is_public' => false,
        'is_required' => false,
        'encrypted' => false,
    ],
];
