<?php

return [
    [
        'key' => 'payroll.reconciliation.enabled',
        'value' => env('PAYROLL_RECONCILIATION_ENABLED', true) ? 'true' : 'false',
        'display_name' => 'Enable Timecard vs Daily Reconciliation',
        'description' => 'Compare user-entered timecards against approved dailies for manual verification.',
        'type' => 'select',
        'group' => 'payroll',
        'options' => [
            'true' => 'Yes',
            'false' => 'No',
        ],
        'order' => 1,
        'is_visible' => true,
        'is_public' => false,
        'is_required' => false,
        'encrypted' => false,
    ],
    [
        'key' => 'payroll.reconciliation.hours_tolerance',
        'value' => (string) env('PAYROLL_RECONCILIATION_HOURS_TOLERANCE', '0.25'),
        'display_name' => 'Reconciliation Hours Tolerance',
        'description' => 'Allowed hours variance before a mismatch is flagged.',
        'type' => 'text',
        'group' => 'payroll',
        'order' => 2,
        'is_visible' => true,
        'is_public' => false,
        'is_required' => false,
        'encrypted' => false,
    ],
    [
        'key' => 'payroll.reconciliation.require_project_match',
        'value' => env('PAYROLL_RECONCILIATION_REQUIRE_PROJECT_MATCH', true) ? 'true' : 'false',
        'display_name' => 'Require Project Match',
        'description' => 'Require project IDs to match during reconciliation.',
        'type' => 'select',
        'group' => 'payroll',
        'options' => [
            'true' => 'Yes',
            'false' => 'No',
        ],
        'order' => 3,
        'is_visible' => true,
        'is_public' => false,
        'is_required' => false,
        'encrypted' => false,
    ],
    [
        'key' => 'payroll.reconciliation.require_cost_code_match',
        'value' => env('PAYROLL_RECONCILIATION_REQUIRE_COST_CODE_MATCH', false) ? 'true' : 'false',
        'display_name' => 'Require Cost Code Match',
        'description' => 'Require cost codes to match during reconciliation when mapping is available.',
        'type' => 'select',
        'group' => 'payroll',
        'options' => [
            'true' => 'Yes',
            'false' => 'No',
        ],
        'order' => 4,
        'is_visible' => true,
        'is_public' => false,
        'is_required' => false,
        'encrypted' => false,
    ],
    [
        'key' => 'payroll.reconciliation.warning_only',
        'value' => env('PAYROLL_RECONCILIATION_WARNING_ONLY', true) ? 'true' : 'false',
        'display_name' => 'Warning Only Reconciliation',
        'description' => 'Do not block payroll finalization when mismatches exist.',
        'type' => 'select',
        'group' => 'payroll',
        'options' => [
            'true' => 'Yes',
            'false' => 'No',
        ],
        'order' => 5,
        'is_visible' => true,
        'is_public' => false,
        'is_required' => false,
        'encrypted' => false,
    ],
];
