<?php

return [
    [
        'key' => 'payroll.reconciliation.enabled',
        'value' => env('PAYROLL_RECONCILIATION_ENABLED', true) ? 'true' : 'false',
        'display_name' => 'Enable Timecard vs Daily Reconciliation',
        'description' => 'Compare user-entered timecards against approved dailies for manual verification.',
        'type' => 'select',
        'group' => 'payroll',
        'options' => [
            'true' => 'Yes',
            'false' => 'No',
        ],
        'order' => 1,
        'is_visible' => true,
        'is_public' => false,
        'is_required' => false,
        'encrypted' => false,
    ],
    [
        'key' => 'payroll.reconciliation.hours_tolerance',
        'value' => (string) env('PAYROLL_RECONCILIATION_HOURS_TOLERANCE', '0.25'),
        'display_name' => 'Reconciliation Hours Tolerance',
        'description' => 'Allowed hours variance before a mismatch is flagged.',
        'type' => 'text',
        'group' => 'payroll',
        'order' => 2,
        'is_visible' => true,
        'is_public' => false,
        'is_required' => false,
        'encrypted' => false,
    ],
    [
        'key' => 'payroll.reconciliation.require_project_match',
        'value' => env('PAYROLL_RECONCILIATION_REQUIRE_PROJECT_MATCH', true) ? 'true' : 'false',
        'display_name' => 'Require Project Match',
        'description' => 'Require project IDs to match during reconciliation.',
        'type' => 'select',
        'group' => 'payroll',
        'options' => [
            'true' => 'Yes',
            'false' => 'No',
        ],
        'order' => 3,
        'is_visible' => true,
        'is_public' => false,
        'is_required' => false,
        'encrypted' => false,
    ],
    [
        'key' => 'payroll.reconciliation.require_cost_code_match',
        'value' => env('PAYROLL_RECONCILIATION_REQUIRE_COST_CODE_MATCH', false) ? 'true' : 'false',
        'display_name' => 'Require Cost Code Match',
        'description' => 'Require cost codes to match during reconciliation when mapping is available.',
        'type' => 'select',
        'group' => 'payroll',
        'options' => [
            'true' => 'Yes',
            'false' => 'No',
        ],
        'order' => 4,
        'is_visible' => true,
        'is_public' => false,
        'is_required' => false,
        'encrypted' => false,
    ],
    [
        'key' => 'payroll.reconciliation.warning_only',
        'value' => env('PAYROLL_RECONCILIATION_WARNING_ONLY', true) ? 'true' : 'false',
        'display_name' => 'Warning Only Reconciliation',
        'description' => 'Do not block payroll finalization when mismatches exist.',
        'type' => 'select',
        'group' => 'payroll',
        'options' => [
            'true' => 'Yes',
            'false' => 'No',
        ],
        'order' => 5,
        'is_visible' => true,
        'is_public' => false,
        'is_required' => false,
        'encrypted' => false,
    ],
    [
        'key' => 'payroll.tax_withholding.federal_table',
        'value' => env('PAYROLL_TAX_WITHHOLDING_FEDERAL_TABLE', '[{"up_to":null,"rate":0.12}]'),
        'display_name' => 'Federal Withholding Table (JSON)',
        'description' => 'Progressive federal withholding brackets as JSON rows: [{"up_to":null,"rate":0.12}].',
        'type' => 'textarea',
        'group' => 'payroll',
        'order' => 6,
        'is_visible' => true,
        'is_public' => false,
        'is_required' => false,
        'encrypted' => false,
    ],
    [
        'key' => 'payroll.tax_withholding.state_table',
        'value' => env('PAYROLL_TAX_WITHHOLDING_STATE_TABLE', '[{"up_to":null,"rate":0.05}]'),
        'display_name' => 'State Withholding Table (JSON)',
        'description' => 'Progressive state withholding brackets as JSON rows: [{"up_to":null,"rate":0.05}].',
        'type' => 'textarea',
        'group' => 'payroll',
        'order' => 7,
        'is_visible' => true,
        'is_public' => false,
        'is_required' => false,
        'encrypted' => false,
    ],
    [
        'key' => 'payroll.tax_withholding.local_table',
        'value' => env('PAYROLL_TAX_WITHHOLDING_LOCAL_TABLE', '[{"up_to":null,"rate":0.01}]'),
        'display_name' => 'Local Withholding Table (JSON)',
        'description' => 'Progressive local withholding brackets as JSON rows: [{"up_to":null,"rate":0.01}].',
        'type' => 'textarea',
        'group' => 'payroll',
        'order' => 8,
        'is_visible' => true,
        'is_public' => false,
        'is_required' => false,
        'encrypted' => false,
    ],
    [
        'key' => 'payroll.tax_withholding.social_security_rate',
        'value' => (string) env('PAYROLL_TAX_WITHHOLDING_SOCIAL_SECURITY_RATE', '0.062'),
        'display_name' => 'Social Security Withholding Rate',
        'description' => 'Social Security withholding rate as decimal (0.062) or percentage (6.2).',
        'type' => 'text',
        'group' => 'payroll',
        'order' => 9,
        'is_visible' => true,
        'is_public' => false,
        'is_required' => false,
        'encrypted' => false,
    ],
    [
        'key' => 'payroll.tax_withholding.medicare_rate',
        'value' => (string) env('PAYROLL_TAX_WITHHOLDING_MEDICARE_RATE', '0.0145'),
        'display_name' => 'Medicare Withholding Rate',
        'description' => 'Medicare withholding rate as decimal (0.0145) or percentage (1.45).',
        'type' => 'text',
        'group' => 'payroll',
        'order' => 10,
        'is_visible' => true,
        'is_public' => false,
        'is_required' => false,
        'encrypted' => false,
    ],
];
