<?php

return [
    [
        'key' => 'app.name',
        'value' => env('APP_NAME', 'Project Manager'),
        'display_name' => 'Application Name',
        'description' => 'The name of your application',
        'type' => 'text',
        'group' => 'app',
        'order' => 1,
        'is_visible' => true,
        'is_public' => true,
        'is_required' => true,
        'encrypted' => false,
    ],
    [
        'key' => 'app.url',
        'value' => env('APP_URL', 'http://localhost'),
        'display_name' => 'Application URL',
        'description' => 'The URL of your application',
        'type' => 'url',
        'group' => 'app',
        'order' => 2,
        'is_visible' => true,
        'is_public' => false,
        'is_required' => true,
        'encrypted' => false,
    ],
    [
        'key' => 'app.timezone',
        'value' => env('APP_TIMEZONE', 'UTC'),
        'display_name' => 'Timezone',
        'description' => 'Application timezone for date/time operations',
        'type' => 'select',
        'group' => 'app',
        'options' => [
            'UTC' => 'UTC (Coordinated Universal Time)',
            'America/New_York' => 'Eastern Time (US & Canada)',
            'America/Chicago' => 'Central Time (US & Canada)',
            'America/Denver' => 'Mountain Time (US & Canada)',
            'America/Los_Angeles' => 'Pacific Time (US & Canada)',
        ],
        'order' => 3,
        'is_visible' => true,
        'is_public' => false,
        'is_required' => true,
        'encrypted' => false,
    ],
    [
        'key' => 'app.debug',
        'value' => env('APP_DEBUG', false) ? 'true' : 'false',
        'display_name' => 'Debug Mode',
        'description' => 'Enable debug mode for development',
        'type' => 'select',
        'group' => 'app',
        'options' => ['true' => 'Enabled', 'false' => 'Disabled'],
        'order' => 4,
        'is_visible' => true,
        'is_public' => false,
        'is_required' => true,
        'encrypted' => false,
    ],
    [
        'key' => 'session.driver',
        'value' => env('SESSION_DRIVER', 'file'),
        'display_name' => 'Session Driver',
        'description' => 'Session storage driver (file, database, redis, etc.)',
        'type' => 'select',
        'group' => 'session',
        'options' => ['file' => 'File', 'database' => 'Database', 'redis' => 'Redis', 'memcached' => 'Memcached', 'array' => 'Array (Testing)'],
        'order' => 1,
        'is_visible' => true,
        'is_public' => false,
        'is_required' => false,
        'encrypted' => false,
    ],
    [
        'key' => 'system.locale',
        'value' => env('SYSTEM_LOCALE', 'en'),
        'display_name' => 'Default Language',
        'description' => 'Default language for the application',
        'type' => 'select',
        'group' => 'system',
        'options' => ['en' => 'English', 'es' => 'Spanish', 'fr' => 'French'],
        'order' => 1,
        'is_visible' => true,
        'is_public' => true,
        'is_required' => true,
        'encrypted' => false,
    ],
    [
        'key' => 'mail.mailer',
        'value' => env('MAIL_MAILER', 'log'),
        'display_name' => 'Mail Driver',
        'description' => 'Default mailer used for outgoing emails.',
        'type' => 'select',
        'group' => 'mail',
        'options' => [
            'smtp' => 'SMTP',
            'sendmail' => 'Sendmail',
            'log' => 'Log',
            'array' => 'Array (Testing)',
        ],
        'order' => 1,
        'is_visible' => true,
        'is_public' => false,
        'is_required' => true,
        'encrypted' => false,
    ],
    [
        'key' => 'mail.from_address',
        'value' => env('MAIL_FROM_ADDRESS', 'hello@example.com'),
        'display_name' => 'From Address',
        'description' => 'Default sender email address.',
        'type' => 'email',
        'group' => 'mail',
        'order' => 2,
        'is_visible' => true,
        'is_public' => false,
        'is_required' => true,
        'encrypted' => false,
    ],
    [
        'key' => 'security.session_timeout',
        'value' => (string) env('SECURITY_SESSION_TIMEOUT', '120'),
        'display_name' => 'Session Timeout (minutes)',
        'description' => 'Maximum idle session duration before logout.',
        'type' => 'number',
        'group' => 'security',
        'order' => 1,
        'is_visible' => true,
        'is_public' => false,
        'is_required' => false,
        'encrypted' => false,
    ],
    [
        'key' => 'features.maintenance_mode',
        'value' => env('FEATURES_MAINTENANCE_MODE', false) ? 'true' : 'false',
        'display_name' => 'Maintenance Mode',
        'description' => 'Enable maintenance mode banner/behavior for the application.',
        'type' => 'select',
        'group' => 'features',
        'options' => ['true' => 'Enabled', 'false' => 'Disabled'],
        'order' => 1,
        'is_visible' => true,
        'is_public' => false,
        'is_required' => false,
        'encrypted' => false,
    ],
];
