<?php

return [
    [
        'key' => 'cpanel.url',
        'value' => env('CPANEL_URL', ''),
        'display_name' => 'cPanel URL',
        'description' => 'cPanel server URL (including protocol).',
        'type' => 'text',
        'group' => 'services',
        'order' => 1,
        'is_visible' => true,
        'is_public' => false,
        'is_required' => false,
        'encrypted' => false,
    ],
    [
        'key' => 'cpanel.username',
        'value' => env('CPANEL_USERNAME', ''),
        'display_name' => 'cPanel Username',
        'description' => 'cPanel username used for API auth.',
        'type' => 'text',
        'group' => 'services',
        'order' => 2,
        'is_visible' => true,
        'is_public' => false,
        'is_required' => false,
        'encrypted' => false,
    ],
    [
        'key' => 'cpanel.api_token',
        'value' => env('CPANEL_API_TOKEN', ''),
        'display_name' => 'cPanel API Token',
        'description' => 'API token used for cPanel requests.',
        'type' => 'password',
        'group' => 'services',
        'order' => 3,
        'is_visible' => true,
        'is_public' => false,
        'is_required' => false,
        'encrypted' => true,
    ],
    [
        'key' => 'cpanel.domain',
        'value' => env('CPANEL_DOMAIN', ''),
        'display_name' => 'cPanel Domain',
        'description' => 'Default domain used for mailbox operations.',
        'type' => 'text',
        'group' => 'services',
        'order' => 4,
        'is_visible' => true,
        'is_public' => false,
        'is_required' => false,
        'encrypted' => false,
    ],
    [
        'key' => 'cpanel.port',
        'value' => (string) env('CPANEL_PORT', 2083),
        'display_name' => 'cPanel Port',
        'description' => 'cPanel API port.',
        'type' => 'number',
        'group' => 'services',
        'order' => 5,
        'is_visible' => true,
        'is_public' => false,
        'is_required' => false,
        'encrypted' => false,
    ],
    [
        'key' => 'cpanel.webmail_port',
        'value' => (string) env('CPANEL_WEBMAIL_PORT', 2096),
        'display_name' => 'cPanel Webmail Port',
        'description' => 'Webmail port for redirect fallback.',
        'type' => 'number',
        'group' => 'services',
        'order' => 6,
        'is_visible' => true,
        'is_public' => false,
        'is_required' => false,
        'encrypted' => false,
    ],
    [
        'key' => 'cpanel.webmail_url',
        'value' => env('CPANEL_WEBMAIL_URL', ''),
        'display_name' => 'cPanel Webmail URL',
        'description' => 'Optional explicit webmail URL.',
        'type' => 'url',
        'group' => 'services',
        'order' => 7,
        'is_visible' => true,
        'is_public' => false,
        'is_required' => false,
        'encrypted' => false,
    ],
    [
        'key' => 'cpanel.default_email_quota',
        'value' => (string) env('CPANEL_DEFAULT_EMAIL_QUOTA', 250),
        'display_name' => 'cPanel Default Email Quota (MB)',
        'description' => 'Default mailbox quota in MB.',
        'type' => 'number',
        'group' => 'services',
        'order' => 8,
        'is_visible' => true,
        'is_public' => false,
        'is_required' => false,
        'encrypted' => false,
    ],
    [
        'key' => 'cpanel.auto_create_emails',
        'value' => env('CPANEL_AUTO_CREATE_EMAILS', false) ? 'true' : 'false',
        'display_name' => 'cPanel Auto Create Emails',
        'description' => 'Automatically create mailbox accounts for eligible users.',
        'type' => 'select',
        'group' => 'services',
        'options' => ['true' => 'Yes', 'false' => 'No'],
        'order' => 9,
        'is_visible' => true,
        'is_public' => false,
        'is_required' => false,
        'encrypted' => false,
    ],
    [
        'key' => 'cpanel.auto_delete_emails',
        'value' => env('CPANEL_AUTO_DELETE_EMAILS', true) ? 'true' : 'false',
        'display_name' => 'cPanel Auto Delete Emails',
        'description' => 'Delete mailbox accounts when users are deleted.',
        'type' => 'select',
        'group' => 'services',
        'options' => ['true' => 'Yes', 'false' => 'No'],
        'order' => 10,
        'is_visible' => true,
        'is_public' => false,
        'is_required' => false,
        'encrypted' => false,
    ],
    [
        'key' => 'cpanel.sync_user_passwords',
        'value' => env('CPANEL_SYNC_USER_PASSWORDS', false) ? 'true' : 'false',
        'display_name' => 'cPanel Sync User Passwords',
        'description' => 'Sync application password changes to mailbox accounts.',
        'type' => 'select',
        'group' => 'services',
        'options' => ['true' => 'Yes', 'false' => 'No'],
        'order' => 11,
        'is_visible' => true,
        'is_public' => false,
        'is_required' => false,
        'encrypted' => false,
    ],
    [
        'key' => 'cpanel.queue_write_operations',
        'value' => env('CPANEL_QUEUE_WRITE_OPERATIONS', false) ? 'true' : 'false',
        'display_name' => 'cPanel Queue Write Operations',
        'description' => 'Queue write-side cPanel operations for resilience.',
        'type' => 'select',
        'group' => 'services',
        'options' => ['true' => 'Yes', 'false' => 'No'],
        'order' => 12,
        'is_visible' => true,
        'is_public' => false,
        'is_required' => false,
        'encrypted' => false,
    ],
    [
        'key' => 'cpanel.idempotency_ttl_seconds',
        'value' => (string) env('CPANEL_IDEMPOTENCY_TTL_SECONDS', 120),
        'display_name' => 'cPanel Idempotency TTL (Seconds)',
        'description' => 'Deduplicate repeated write operations within this window.',
        'type' => 'number',
        'group' => 'services',
        'order' => 13,
        'is_visible' => true,
        'is_public' => false,
        'is_required' => false,
        'encrypted' => false,
    ],
    [
        'key' => 'cpanel.queue_tries',
        'value' => (string) env('CPANEL_QUEUE_TRIES', 3),
        'display_name' => 'cPanel Queue Retries',
        'description' => 'Maximum number of attempts for queued write operations.',
        'type' => 'number',
        'group' => 'services',
        'order' => 14,
        'is_visible' => true,
        'is_public' => false,
        'is_required' => false,
        'encrypted' => false,
    ],
    [
        'key' => 'cpanel.queue_backoff',
        'value' => env('CPANEL_QUEUE_BACKOFF', ''),
        'display_name' => 'cPanel Queue Backoff',
        'description' => 'Comma-separated backoff seconds for queued retries.',
        'type' => 'text',
        'group' => 'services',
        'order' => 15,
        'is_visible' => true,
        'is_public' => false,
        'is_required' => false,
        'encrypted' => false,
    ],
    [
        'key' => 'cpanel.failure_threshold',
        'value' => (string) env('CPANEL_FAILURE_THRESHOLD', 5),
        'display_name' => 'cPanel Failure Threshold',
        'description' => 'Consecutive failures before cPanel cooldown activates.',
        'type' => 'number',
        'group' => 'services',
        'order' => 16,
        'is_visible' => true,
        'is_public' => false,
        'is_required' => false,
        'encrypted' => false,
    ],
    [
        'key' => 'cpanel.cooldown_seconds',
        'value' => (string) env('CPANEL_COOLDOWN_SECONDS', 300),
        'display_name' => 'cPanel Cooldown Seconds',
        'description' => 'Skip write operations while cooldown is active.',
        'type' => 'number',
        'group' => 'services',
        'order' => 17,
        'is_visible' => true,
        'is_public' => false,
        'is_required' => false,
        'encrypted' => false,
    ],
    [
        'key' => 'cpanel.telemetry_key_prefix',
        'value' => env('CPANEL_TELEMETRY_KEY_PREFIX', ''),
        'display_name' => 'cPanel Telemetry Key Prefix',
        'description' => 'Cache key prefix for cPanel success/failure counters.',
        'type' => 'text',
        'group' => 'services',
        'order' => 18,
        'is_visible' => true,
        'is_public' => false,
        'is_required' => false,
        'encrypted' => false,
    ],
    [
        'key' => 'cpanel.verify_ssl',
        'value' => env('CPANEL_VERIFY_SSL', true) ? 'true' : 'false',
        'display_name' => 'cPanel Verify SSL',
        'description' => 'Require SSL certificate verification for cPanel API requests.',
        'type' => 'select',
        'group' => 'services',
        'options' => ['true' => 'Yes', 'false' => 'No'],
        'order' => 19,
        'is_visible' => true,
        'is_public' => false,
        'is_required' => false,
        'encrypted' => false,
    ],
];
