<?php

use App\Core\Settings\DTO\Setting;
use App\Core\Settings\DTO\SettingType;
use App\Core\Settings\DTO\SettingFormFieldType;

return [
    new Setting(
        key: 'zoom.account_id',
        type: SettingType::String,
        formFieldType: SettingFormFieldType::Text,
        value: env('ZOOM_ACCOUNT_ID', ''),
        display_name: 'Zoom Account ID',
        description: 'Zoom Server-to-Server OAuth account identifier.',
        group: 'services.zoom',
        options: null,
        order: 1,
        is_visible: true,
        is_public: false,
        is_required: false,
        encrypted: false,
    ),
    new Setting(
        key: 'zoom.client_id',
        type: SettingType::String,
        formFieldType: SettingFormFieldType::Text,
        value: env('ZOOM_CLIENT_ID', ''),
        display_name: 'Zoom Client ID',
        description: 'Zoom OAuth client ID used for SMS API authentication.',
        group: 'services.zoom',
        options: null,
        order: 2,
        is_visible: true,
        is_public: false,
        is_required: false,
        encrypted: false,
    ),
    new Setting(
        key: 'zoom.client_secret',
        type: SettingType::String,
        formFieldType: SettingFormFieldType::Password,
        value: env('ZOOM_CLIENT_SECRET', ''),
        display_name: 'Zoom Client Secret',
        description: 'Zoom OAuth client secret used for token acquisition.',
        group: 'services.zoom',
        options: null,
        order: 3,
        is_visible: true,
        is_public: false,
        is_required: false,
        encrypted: true,
    ),
    new Setting(
        key: 'zoom.token_url',
        type: SettingType::String,
        formFieldType: SettingFormFieldType::Text,
        value: env('ZOOM_TOKEN_URL', 'https://zoom.us/oauth/token'),
        display_name: 'Zoom Token URL',
        description: 'OAuth token endpoint for Zoom Server-to-Server credentials.',
        group: 'services.zoom',
        options: null,
        order: 4,
        is_visible: true,
        is_public: false,
        is_required: false,
        encrypted: false,
    ),
    new Setting(
        key: 'zoom.from_number',
        type: SettingType::String,
        formFieldType: SettingFormFieldType::Text,
        value: env('ZOOM_SMS_FROM_NUMBER', ''),
        display_name: 'Zoom SMS From Number',
        description: 'E.164 sender phone number used for outbound SMS.',
        group: 'services.zoom',
        options: null,
        order: 5,
        is_visible: true,
        is_public: false,
        is_required: false,
        encrypted: false,
    ),
    new Setting(
        key: 'zoom.zoom_user_id',
        type: SettingType::String,
        formFieldType: SettingFormFieldType::Text,
        value: env('ZOOM_USER_ID', ''),
        display_name: 'Zoom User ID',
        description: 'Zoom user ID owning the sender number for consent lookups.',
        group: 'services.zoom',
        options: null,
        order: 6,
        is_visible: true,
        is_public: false,
        is_required: false,
        encrypted: false,
    ),
    new Setting(
        key: 'zoom.sms_campaign_id',
        type: SettingType::String,
        formFieldType: SettingFormFieldType::Text,
        value: env('ZOOM_SMS_CAMPAIGN_ID', ''),
        display_name: 'Zoom SMS Campaign ID',
        description: 'Campaign identifier used for consent status synchronization.',
        group: 'services.zoom',
        options: null,
        order: 7,
        is_visible: true,
        is_public: false,
        is_required: false,
        encrypted: false,
    ),
    new Setting(
        key: 'zoom.api_base_url',
        type: SettingType::String,
        formFieldType: SettingFormFieldType::Text,
        value: env('ZOOM_API_BASE_URL', 'https://api.zoom.us/v2'),
        display_name: 'Zoom API Base URL',
        description: 'Base API URL used for Zoom SMS and consent endpoints.',
        group: 'services.zoom',
        options: null,
        order: 8,
        is_visible: true,
        is_public: false,
        is_required: false,
        encrypted: false,
    ),
    new Setting(
        key: 'zoom.token_cache_ttl',
        type: SettingType::Integer,
        formFieldType: SettingFormFieldType::Number,
        value: (string) env('ZOOM_TOKEN_CACHE_TTL', 3590),
        display_name: 'Zoom Token Cache TTL (Seconds)',
        description: 'Token cache duration in seconds before requesting a new token.',
        group: 'services.zoom',
        options: null,
        order: 9,
        is_visible: true,
        is_public: false,
        is_required: false,
        encrypted: false,
    ),
    new Setting(
        key: 'zoom.timeout',
        type: SettingType::Integer,
        formFieldType: SettingFormFieldType::Number,
        value: (string) env('ZOOM_TIMEOUT', 15),
        display_name: 'Zoom Request Timeout (Seconds)',
        description: 'HTTP request timeout for Zoom API calls.',
        group: 'services.zoom',
        options: null,
        order: 10,
        is_visible: true,
        is_public: false,
        is_required: false,
        encrypted: false,
    ),
    new Setting(
        key: 'zoom.retry_times',
        type: SettingType::Integer,
        formFieldType: SettingFormFieldType::Number,
        value: (string) env('ZOOM_RETRY_TIMES', 3),
        display_name: 'Zoom Retry Attempts',
        description: 'Number of retry attempts for transient Zoom API failures.',
        group: 'services.zoom',
        options: null,
        order: 11,
        is_visible: true,
        is_public: false,
        is_required: false,
        encrypted: false,
    ),
    new Setting(
        key: 'zoom.retry_sleep_ms',
        type: SettingType::Integer,
        formFieldType: SettingFormFieldType::Number,
        value: (string) env('ZOOM_RETRY_SLEEP_MS', 1000),
        display_name: 'Zoom Retry Sleep (Milliseconds)',
        description: 'Delay between retry attempts in milliseconds.',
        group: 'services.zoom',
        options: null,
        order: 12,
        is_visible: true,
        is_public: false,
        is_required: false,
        encrypted: false,
    ),
];
