<?php

return [
    [
        'key' => 'assets.storage_disk',
        'value' => env('ASSETS_STORAGE_DISK', 'local'),
        'display_name' => 'Asset Storage Disk',
        'description' => 'Default filesystem disk used to store uploaded assets',
        'type' => 'select',
        'group' => 'assets',
        'options' => [
            'local' => 'Local Storage',
            's3' => 'Amazon S3',
            'public' => 'Public Storage',
        ],
        'order' => 1,
        'is_visible' => true,
        'is_public' => false,
        'is_required' => false,
        'encrypted' => false,
    ],
    [
        'key' => 'assets.allowed_types',
        'value' => env('ASSETS_ALLOWED_TYPES', 'pdf,doc,docx,xls,xlsx,ppt,pptx,txt,jpg,jpeg,png,gif,webp,svg'),
        'display_name' => 'Allowed File Types',
        'description' => 'Comma-separated default allowed file extensions. Domains may override this.',
        'type' => 'text',
        'group' => 'assets',
        'order' => 2,
        'is_visible' => true,
        'is_public' => false,
        'is_required' => false,
        'encrypted' => false,
    ],
    [
        'key' => 'assets.max_file_size',
        'value' => (string) env('ASSETS_MAX_FILE_SIZE', '10240'),
        'display_name' => 'Maximum File Size (KB)',
        'description' => 'Default maximum upload size in kilobytes. Domains may override this.',
        'type' => 'number',
        'group' => 'assets',
        'order' => 3,
        'is_visible' => true,
        'is_public' => false,
        'is_required' => false,
        'encrypted' => false,
    ],
    [
        'key' => 'assets.deduplicate',
        'value' => env('ASSETS_DEDUPLICATE', true) ? 'true' : 'false',
        'display_name' => 'Deduplicate Identical Files',
        'description' => 'Store identical file content once and reference it from multiple records',
        'type' => 'select',
        'group' => 'assets',
        'options' => [
            'true' => 'Yes',
            'false' => 'No',
        ],
        'order' => 4,
        'is_visible' => true,
        'is_public' => false,
        'is_required' => false,
        'encrypted' => false,
    ],
];
